# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35d0081190ee024fcc9c1b99e437955afe3c207835530d9bb10e024c97e2e539ff6f052fab0937151628561e548345a6ff41f08b3a857995f4c3fff96bac24f2

test:
  secret_key_base: 239af9668733f492bc3b2fc063d017134da999a6d7ba0e97ff0b5ebfe97f7d5828e1dd2f99711ffeeabe0e1cd3a81906adbc33bec26e0fbb67aab88eb086fb65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
